# -*- coding: utf-8 -*-
"""P1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmKSGbKhf6yh3RORNjrpCQgenvGsGr0A
"""

now=input().split(" ")
now_x=int(now[0])
now_y=int(now[1])
nextp=input().split(" ")
next_x=int(nextp[0])
next_y=int(nextp[1])


checkerboard[now_x][now_y]=1

temp_x=abs(next_x-now_x)
temp_y=abs(next_y-now_y)
if temp_x==0 and temp_y==0:
    print("No")


if abs(temp_x)==abs(temp_y):
    for i in range(1,abs(temp_x)+1):
        if next_x>now_x and next_y>now_y:
            if checkerboard[now_x+i][now_y+i]==1:
                print("No")
                break
        elif next_x<now_x and next_y>now_y:
            if checkerboard[now_x-i][now_y+i]==1:
                print("No")
                break
        elif next_x<now_x and next_y<now_y:
            if checkerboard[now_x-i][now_y-i]==1:
                print("No")
                break
        else:
            if checkerboard[now_x+i][now_y-i]==1:
                print("No")
                break
        if i==abs(temp_x):
            print("Yes")
elif abs(temp_x)==0 and abs(temp_y)!=0:
    for i in range(1,abs(temp_y)+1):
        if next_y>now_y:
            if checkerboard[now_x][now_y+i]==1:
                print("No")
                break
        else:
            if checkerboard[now_x][now_y-i]==1:
                print("No")
                break
        if i==abs(temp_y):
            print("Yes")
elif abs(temp_x)!=0 and abs(temp_y)==0:
    for i in range(1,abs(temp_x)+1):
        if next_x>now_x:
            if checkerboard[now_x+i][now_y]==1:
                print("No")
                break
        else:
            if checkerboard[now_x-i][now_y]==1:
                print("No")
                break
        if i==abs(temp_x):
            print("Yes")
else:
    print("No")